{
 "title": "Port Health Checker",
 "tags": [
  "port-checker",
  "monitoring"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": {
     "query": "label_values(port_check_status,service)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$service",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "repeat": "service",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service, port)(port_check_status{service=~\"$service\"})",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Port Latency (ms)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max by (service, port) (port_check_latency_ms)",
     "legendFormat": "{{service}} (port {{port}})"
    }
   ]
  },
  {
   "title": "port status",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "max by (service, port)(port_check_status)",
     "legendFormat": "{{label_name}}"
    }
   ]
  }
 ]
}